name: Metrics
on:
  # daily update
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # is secret, shhhhh
          token: ${{ secrets.METRICS_TOKEN }}


          user: souhail-bel
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Tunis
          config_animation: yes

          plugin_introduction: yes
          plugin_introduction_title: Greetings, internauts!
          plugin_introduction_text: I'm a curious guy, with passion for mathematics, physics and computer science.

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8

          # my streakkkk
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # my achievements yooo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 8

          plugin_lines: yes

          plugin_monkeytype: yes
          plugin_monkeytype_user: loom_0
